SarShop.WebUI/Controllers/CardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using SarShop.BL.Repositories;
using SarShop.DAL.Entities;
using SarShop.DAL.Migrations;
using SarShop.WebUI.Models;
using SarShop.WebUI.Tools;
using SarShop.WebUI.ViewModels;

namespace SarShop.WebUI.Controllers
{
	public class CardController : Controller
	{

		IRepository<Product> repoProduct;
		IRepository<City> repoCity;
		IRepository<Order> repoOrder;
		IRepository<OrderDetail> repoOrderDetail;
		public CardController(IRepository<Product> _repoProduct, IRepository<City> _repoCity, IRepository<Order> _repoOrder, IRepository<OrderDetail> _repoOrderDetail)
		{
			repoProduct = _repoProduct;
			repoCity = _repoCity;
			repoOrder = _repoOrder;
			repoOrderDetail = _repoOrderDetail;

		}

		[Route("/sepetim")]
		public IActionResult Index()
		{
			if (Request.Cookies["MyCart"] != null)
			{
				var cartItems = JsonConvert.DeserializeObject<List<Cart>>(Request.Cookies["MyCart"]);

				if (cartItems.Count > 0)
				{
					return View(cartItems);
				}
			}

			return Redirect("/");
		}

		[Route("/sepetim/sayiver")]
		public int GetCartCount()
		{
			if (Request.Cookies["MyCart"] != null)
			{
				return JsonConvert.DeserializeObject<List<Cart>>(Request.Cookies["MyCart"]).Sum(x => x.Quantity);
			}
			else return 0;
		}

		[Route("/sepetim/sil")]
		public string RemoveCart(int productid)
		{
			if (Request.Cookies["MyCart"] != null)
			{
				List<Cart> carts = JsonConvert.DeserializeObject<List<Cart>>(Request.Cookies["MyCart"]);
				carts.Remove(carts.FirstOrDefault(x => x.ID == productid));
				CookieOptions cookieOptions = new();
				cookieOptions.Expires = DateTime.Now.AddDays(3);
				Response.Cookies.Append("MyCart", JsonConvert.SerializeObject(carts), cookieOptions);
				return "OK";
			}
			else return "";
		}


		[Route("/sepetim/ekle")]
		public string AddCart(int productid, int quantity)
		{
			Product product = repoProduct.GetAll(x => x.ID == productid).Include(x => x.ProductPictures).FirstOrDefault() ?? null;
			if (product != null)
			{
				Cart cart = new Cart
				{
					ID = product.ID,
					Name = product.Name,
					Picture = product.ProductPictures.Any() ?
					product.ProductPictures.FirstOrDefault().Picture : "/img/urunhazirlaniyor.jpg",
					Price = product.Price,
					Quantity = quantity
				};
				List<Cart> carts = new List<Cart>();
				bool urunVarmi = false;
				if (Request.Cookies["MyCart"] != null)
				{
					carts = JsonConvert.DeserializeObject<List<Cart>>(Request.Cookies["MyCart"]);

					foreach (Cart _cart in carts)
					{
						if (_cart.ID == productid)
						{
							urunVarmi = true;
							_cart.Quantity += quantity;
							if (product.Stock < _cart.Quantity) _cart.Quantity = product.Stock;
							break;

						}


					}
				}
				if (urunVarmi == false) carts.Add(cart);
				CookieOptions cookieOptions = new();
				cookieOptions.Expires = DateTime.Now.AddDays(3);
				Response.Cookies.Append("MyCart", JsonConvert.SerializeObject(carts), cookieOptions);
				return product.Name;
			}
			else return "";

		}




		//[Authorize(AuthenticationSchemes = "SarShopMemberAuth"),Route("/sepetim/tamamla")]
		[Route("/sepetim/tamamla")]
		public IActionResult Complete()
		{
			OrderVM orderVM = new OrderVM
			{
				Carts = JsonConvert.DeserializeObject<List<Cart>>(Request.Cookies["MyCart"]),
				Cities = repoCity.GetAll().OrderBy(x => x.Name)
			};
			return View(orderVM);
		}

		[Route("/sepetim/tamamla"), HttpPost]
		public async Task<IActionResult> Complete(OrderVM model)
		{
			model.Order.RecDate = DateTime.Now;
			model.Order.IPNO = HttpContext.Connection.RemoteIpAddress.ToString();
			model.Order.OrderStatus = EOrderStatus.Hazirlaniyor;
			string orderNumber = repoOrder.GetAll().Any() ? repoOrder.GetAll().OrderByDescending(x => x.ID).FirstOrDefault().ID.ToString() : "1" + DateTime.Now.Millisecond.ToString() + DateTime.Now.Second.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Hour.ToString();
			if (orderNumber.Length > 10) orderNumber = orderNumber.Substring(0, 10);
			model.Order.OrderNumber = orderNumber;
			await repoOrder.Add(model.Order);
			foreach (Cart cart in JsonConvert.DeserializeObject<List<Cart>>(Request.Cookies["MyCart"]))
			{
				OrderDetail orderDetail = new OrderDetail { OrderID = model.Order.ID, Name = cart.Name, Picture = cart.Picture, Price = cart.Price, ProductID = cart.ID, Quantity = cart.Quantity };
				await repoOrderDetail.Add(orderDetail);
			}
			Response.Cookies.Delete("MyCart");
			
			TempData["Siparis"] ="Sayın"+ model.Order.Name + " " + model.Order.Surname + " siparişiniz başarıyla alındı...";
			return Redirect("/");
		}
	}
}

SarShop.WebUI/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SarShop.BL.Repositories;
using SarShop.DAL.Entities;
using SarShop.WebUI.ViewModels;

namespace SarShop.WebUI.Controllers
{
	public class ShopController : Controller
	{
		IRepository<Category> repoCate;
		IRepository<Product> repoProduct;
		public ShopController(IRepository<Category> _repoCate, IRepository<Product> _repoProduct)
		{
			repoCate = _repoCate;
			repoProduct = _repoProduct;
		}
        public IActionResult Index()
        {
            var categories = repoCate.GetAll().Include(x => x.SubCategories).OrderBy(x => x.DisplayIndex).ThenBy(x => x.Name);
            var products = repoProduct.GetAll().Include(x => x.ProductPictures).OrderBy(x => Guid.NewGuid()).Take(50);
            ShopVM shopVM = new ShopVM
            {
                Categories = categories,
                Products = products,
            };
            return View(shopVM);
        }


        [HttpGet]
        public IActionResult GetProductsByCategory(int? categoryID)
        {
            if (categoryID == null)
            {
                // Eğer categoryID null ise, tüm ürünleri döndür
                var allProducts = repoProduct.GetAll().Include(x => x.ProductPictures).ToList();
                return PartialView("ProductsByCategory", allProducts);
            }

            // Seçilen kategoriye ait ürünleri bulun
            var productsByCategory = repoProduct.GetAll()
                .Include(x => x.ProductPictures)
                .Where(p => p.ProductCategories.Any(pc => pc.CategoryID == categoryID))
                .ToList();

            return PartialView("ProductsByCategory", productsByCategory);
        }





        [Route("detay/{name}-{id}")]
		public IActionResult ProductDetail(int id,string name)
		{

			Product product= repoProduct.GetAll().Include(x => x.ProductPictures).FirstOrDefault(x => x.ID == id);
			ProductDetailVM vm = new ProductDetailVM
			{
				Product = product,
				RelatedProducts = repoProduct.GetAll(x => x.BrandID == product.BrandID && x.ID != id).Include(i=>i.ProductPictures).OrderBy(x=>Guid.NewGuid()).Take(3) 
		};
			return View(vm);	
		}
	}
}

SarShop.WebUI/Views/Shared/Components/Header/Default.cshtml
<!-- Start Top Nav -->
	<nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
		<div class="container text-light">
			<div class="w-100 d-flex justify-content-between">
				<div>
					<i class="fa fa-envelope mx-2"></i>
					<a class="navbar-sm-brand text-light text-decoration-none" href="mailto:info@company.com">info@company.com</a>
					<i class="fa fa-phone mx-2"></i>
					<a class="navbar-sm-brand text-light text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
				</div>
				<div>
					<a class="text-light" href="https://fb.com/templatemo" target="_blank" rel="sponsored"><i class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
					<a class="text-light" href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
					<a class="text-light" href="https://twitter.com/" target="_blank"><i class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
					<a class="text-light" href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin fa-sm fa-fw"></i></a>
				</div>
			</div>
		</div>
	</nav>
	<!-- Close Top Nav -->
	<!-- Header -->
	<nav class="navbar navbar-expand-lg navbar-light shadow">
		<div class="container d-flex justify-content-between align-items-center">

		<a class="navbar-brand text-success logo h1 align-self-center" asp-controller="Home" asp-action="Index" style="color: #006400;">
			Sar Shop
		</a>

			<button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
				<div class="flex-fill">
					<ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
						<li class="nav-item">
							<a class="nav-link" asp-controller="Home"asp-action="Index">Ana Sayfa</a>
						</li>	
					
					<li class="nav-item">
						<a class="nav-link" asp-controller="Shop" asp-action="Index">Alışveriş</a>
					</li>
						<li class="nav-item">
							<a class="nav-link" href="contact.html">Contact</a>
						</li>
					</ul>
				</div>
				<div class="navbar align-self-center d-flex">
					<div class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3">
						<div class="input-group">
							<input type="text" class="form-control" id="inputMobileSearch" placeholder="Search ...">
							<div class="input-group-text">
								<i class="fa fa-fw fa-search"></i>
							</div>
						</div>
					</div>

				 <a class="nav-icon position-relative text-decoration-none" asp-controller="Card" asp-action="Index">
						<i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>
					<span class="cartCounter position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark"></span>
					
					</a>
			
				</div>
			</div>

		</div>
	</nav>
	<!-- Close Header -->