SarShop.WebUI/Areas/admin/Controllers/BrandController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SarShop.BL.Repositories;
using SarShop.DAL.Entities;

namespace SarShop.WebUI.Areas.admin.Controllers
{
	[Area("admin"), Authorize]
	public class BrandController : Controller
	{
		IRepository<Brand> repoBrand;
		public BrandController(IRepository<Brand> _repoBrand)
		{
			repoBrand = _repoBrand;
		}

		[Route("/admin/marka")]
		public IActionResult Index()
		{
			return View(repoBrand.GetAll());
		}

		[Route("/admin/marka/yeni")]
		public IActionResult New()
		{
			return View();
		}
		[Route("admin/marka/yeni"), HttpPost]
		public async Task <IActionResult> New(Brand model)
		{
		
		     await repoBrand.Add(model);
			return Redirect("/admin/marka");
		}

		[Route("/admin/marka/duzenle")]
		public IActionResult Edit(int id)
		{
			return View(repoBrand.GetBy(x=>x.ID==id));
		}

		[Route("/admin/marka/duzenle"),HttpPost]
		public async Task<IActionResult> Edit(Brand model)
		{
			
		   await repoBrand.Update(model);
			return Redirect("/admin/marka");
		}

		[Route("/admin/marka/sil"), HttpPost]
        public async Task<string> Delete(int id)
        {
			try
			{
				Brand brand = repoBrand.GetBy(x => x.ID == id) ?? null;
				if (brand != null)await repoBrand.Delete(brand);
				return "OK";
			}
			catch (Exception ex)
			{

				return ex.Message;
			}
		}
	}
}

SarShop.WebUI/Areas/admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SarShop.BL.Repositories;
using SarShop.DAL.Entities;
using SarShop.WebUI.Areas.admin.ViewModels;

namespace SarShop.WebUI.Areas.admin.Controllers
{
	[Area("admin"), Authorize]
	public class ProductController : Controller
	{
        IRepository<Brand> repoBrand;
        IRepository<Product> repoProduct;
		IRepository<Category> repoCategory;
		IRepository<ProductCategory> repoProductCategory;
		public ProductController(IRepository<Product> _repoProduct, IRepository<Brand> _repoBrand, IRepository<Category> _repoCategory,
        IRepository<ProductCategory> _repoProductCategory)
		{
			repoCategory = _repoCategory;
			repoBrand = _repoBrand;
			repoProduct = _repoProduct;
			repoProductCategory = _repoProductCategory;
		}

		[Route("/admin/urun")]
		public IActionResult Index()
		{
			return View(repoProduct.GetAll().Include(i=>i.Brand).Include(i=>i.ProductCategories).ThenInclude(t=>t.Category));
		}

		[Route("/admin/urun/yeni")]
		public IActionResult New()
		{

			ProductVM productVM = new ProductVM
			{
				Brands = repoBrand.GetAll().OrderBy(x => x.Name),
				Categories = repoCategory.GetAll().OrderBy(x => x.Name).ToList()
			};


			return View(productVM);
		}
		[Route("admin/urun/yeni"), HttpPost]
		public async Task <IActionResult> New(ProductVM model)
		{
		    await repoProduct.Add(model.Product);
			if (model.CategoryIDs.Length>0)
			{
				for (int i = 0; i < model.CategoryIDs.Length; i++)
				{
					await repoProductCategory.Add(new ProductCategory { ProductID = model.Product.ID, CategoryID = model.CategoryIDs[i] });
					
				}
			}
			return Redirect("/admin/urun");
		}

		[Route("/admin/urun/duzenle")]
		public IActionResult Edit(int id)
		{
			ProductVM productVM = new ProductVM
			{
				Brands = repoBrand.GetAll().OrderBy(x => x.Name),
				Categories = repoCategory.GetAll().OrderBy(x => x.Name).ToList(),
				Product=repoProduct.GetAll().Include(x=>x.ProductCategories).FirstOrDefault(x=>x.ID==id),
			};

			return View(productVM);
		}

		[Route("/admin/urun/duzenle"),HttpPost]
		public async Task<IActionResult> Edit(ProductVM model)
		{
			await repoProduct.Update(model.Product);
			await repoProductCategory.DeleteRange(repoProductCategory.GetAll(x => x.ProductID == model.Product.ID));
			if (model.CategoryIDs.Length > 0)
			{
				for (int i = 0; i < model.CategoryIDs.Length; i++)
				{
					await repoProductCategory.Add(new ProductCategory { ProductID = model.Product.ID, CategoryID = model.CategoryIDs[i] });
				}
			}
			return Redirect("/admin/urun");
		}

		[Route("/admin/urun/sil"),HttpPost]
		public async Task <string> Delete(int id)
		{
			try
			{
				Product product = repoProduct.GetBy(x => x.ID == id) ?? null;
				if (product != null) await repoProduct.Delete(product);
				return "OK";
			}
			catch (Exception ex)
			{

				return ex.Message;
			}
		}
	}
}

SarShop.WebUI/Areas/admin/Controllers/SlideController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SarShop.BL.Repositories;
using SarShop.DAL.Entities;

namespace SarShop.WebUI.Areas.admin.Controllers
{
	[Area("admin"), Authorize]
	public class SlideController : Controller
	{
		IRepository<Slide> repoSlide;
		public SlideController(IRepository<Slide> _repoSlide)
		{
			repoSlide = _repoSlide;
		}

		[Route("/admin/slayt")]
		public IActionResult Index()
		{
			return View(repoSlide.GetAll());
		}

		[Route("/admin/slayt/yeni")]
		public IActionResult New()
		{
			return View();
		}
		[Route("admin/slayt/yeni"), HttpPost]
		public async Task <IActionResult> New(Slide model)
		{
			if (Request.Form.Files.Any())
			{
				if (!Directory.Exists(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "slide"))) Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "slide"));
				string dosyaAdi =(DateTime.Now.Minute+DateTime.Now.Millisecond)+Request.Form.Files["Picture"].FileName;
				using(FileStream stream =new FileStream(Path.Combine(Directory.GetCurrentDirectory(),"wwwroot","img","slide",dosyaAdi),FileMode.Create))
				{
					await Request.Form.Files["Picture"].CopyToAsync(stream);
				}

				model.Picture = "/img/slide/" + dosyaAdi;
			}
		     await repoSlide.Add(model);
			return Redirect("/admin/slayt");
		}

		[Route("/admin/slayt/duzenle")]
		public IActionResult Edit(int id)
		{
			return View(repoSlide.GetBy(x=>x.ID==id));
		}

		[Route("/admin/slayt/duzenle"),HttpPost]
		public async Task<IActionResult> Edit(Slide model)
		{
			if (Request.Form.Files.Any())
			{
				if (!Directory.Exists(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "slide"))) Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "slide"));
				string dosyaAdi = (DateTime.Now.Minute + DateTime.Now.Millisecond) + Request.Form.Files["Picture"].FileName;
				using (FileStream stream = new FileStream(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "slide", dosyaAdi), FileMode.Create))
				{
					await Request.Form.Files["Picture"].CopyToAsync(stream);
				}

				model.Picture = "/img/slide" + dosyaAdi;
			}
		   await repoSlide.Update(model);
			return Redirect("/admin/slayt");
		}

		[Route("/admin/slayt/sil"), HttpPost]
        public async Task<string> Delete(int id)
        {
			try
			{
				Slide slide = repoSlide.GetBy(x => x.ID == id) ?? null;
				if (slide != null) await repoSlide.Delete(slide);
				return "OK";
			}
			catch (Exception ex)
			{

				return ex.Message;
			}
		}
	}
}

SarShop.WebUI/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using SarShop.BL.Repositories;
using SarShop.DAL.Entities;
using SarShop.DAL.Migrations;

namespace SarShop.WebUI.Controllers
{
	public class AboutController : Controller
	{
		IRepository<Aboutt> repoAbout;
		public AboutController(IRepository<Aboutt> _repoAbout)
		{
			repoAbout = _repoAbout;
		}
		[Route("/hakkimizda/{id}/{title}")]
		public IActionResult Index(int id , string title)
		{
			var response = repoAbout.GetBy(x => x.ID == id);
			return View(response);
		}
	}
}

SarShop.WebUI/Areas/admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<!-- Meta, title, CSS, favicons, etc. -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" href="/admin/images/favicon.ico" type="image/ico" />

	<title>Gentelella Alela!</title>

	<!-- Bootstrap -->
	<link href="/admin/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	<!-- Font Awesome -->
	<link href="/admin/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
	<!-- NProgress -->
	<link href="/admin/vendors/nprogress/nprogress.css" rel="stylesheet">
	<!-- iCheck -->
	<link href="/admin/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

	<!-- bootstrap-progressbar -->
	<link href="/admin/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
	<!-- JQVMap -->
	<link href="/admin/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet" />
	<!-- bootstrap-daterangepicker -->
	<link href="/admin/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

	<!-- Custom Theme Style -->
	<link href="/admin/build/css/custom.min.css" rel="stylesheet">
</head>

<body class="nav-md">
	<div class="container body">
		<div class="main_container">
			<div class="col-md-3 left_col">
				<div class="left_col scroll-view">
					<div class="navbar nav_title" style="border: 0;">
						<a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
					</div>

					<div class="clearfix"></div>

					<!-- menu profile quick info -->
					<div class="profile clearfix">
						<div class="profile_pic">
							<img src="/admin/images/img.jpg" alt="..." class="img-circle profile_img">
						</div>
						<div class="profile_info">
							<span>Welcome,</span>
							<h2>@User.Claims.FirstOrDefault(x=>x.Type==ClaimTypes.Name).Value</h2>
						</div>
					</div>
					<!-- /menu profile quick info -->

					<br />

					<!-- sidebar menu -->
					<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
						<div class="menu_section">
							<h3>General</h3>
							<ul class="nav side-menu">
								<li>
									<a asp-area="admin" asp-controller="Home" asp-action="Index"><i class="fa fa-home"></i> Ana Sayfa</a>
								</li>
								<li>
									<a asp-area="admin" asp-controller="Slide" asp-action="Index"><i class="fa fa-edit"></i> Slayt Yönetimi</a>
								</li>

								<li>
									<a asp-area="admin" asp-controller="Brand" asp-action="Index"><i class="fa fa-desktop"></i> Markalar</a>
								</li>

								<li>
									<a asp-area="admin" asp-controller="Category" asp-action="Index"><i class="fa fa-table"></i> Kategoriler</a>
								</li>

								<li>
									<a asp-area="admin" asp-controller="Product" asp-action="Index"><i class="fa fa-bar-chart-o"></i> Ürün Yönetimi</a>
								</li>

								<li>
									<a asp-area="admin" asp-controller="About" asp-action="Index"><i class="fa fa-bar-chart-o"></i>Footer Yönetimi</a>
								</li>

												
								<li>
									<a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><a href="chartjs.html">Chart JS</a></li>
										<li><a href="chartjs2.html">Chart JS2</a></li>
										<li><a href="morisjs.html">Moris JS</a></li>
										<li><a href="echarts.html">ECharts</a></li>
										<li><a href="other_charts.html">Other Charts</a></li>
									</ul>
								</li>
								<li>
									<a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
										<li><a href="fixed_footer.html">Fixed Footer</a></li>
									</ul>
								</li>
							</ul>
						</div>
						<div class="menu_section">
							<h3>Live On</h3>
							<ul class="nav side-menu">
								<li>
									<a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><a href="e_commerce.html">E-commerce</a></li>
										<li><a href="projects.html">Projects</a></li>
										<li><a href="project_detail.html">Project Detail</a></li>
										<li><a href="contacts.html">Contacts</a></li>
										<li><a href="profile.html">Profile</a></li>
									</ul>
								</li>
								<li>
									<a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><a href="page_403.html">403 Error</a></li>
										<li><a href="page_404.html">404 Error</a></li>
										<li><a href="page_500.html">500 Error</a></li>
										<li><a href="plain_page.html">Plain Page</a></li>
										<li><a href="login.html">Login Page</a></li>
										<li><a href="pricing_tables.html">Pricing Tables</a></li>
									</ul>
								</li>
								<li>
									<a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><a href="#level1_1">Level One</a>
										<li>
											<a>Level One<span class="fa fa-chevron-down"></span></a>
											<ul class="nav child_menu">
												<li class="sub_menu">
													<a href="level2.html">Level Two</a>
												</li>
												<li>
													<a href="#level2_1">Level Two</a>
												</li>
												<li>
													<a href="#level2_2">Level Two</a>
												</li>
											</ul>
										</li>
										<li>
											<a href="#level1_2">Level One</a>
										</li>
									</ul>
								</li>
								<li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>
							</ul>
						</div>

					</div>
					<!-- /sidebar menu -->
					<!-- /menu footer buttons -->
					<div class="sidebar-footer hidden-small">
						<a data-toggle="tooltip" data-placement="top" title="Settings">
							<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
						</a>
						<a data-toggle="tooltip" data-placement="top" title="FullScreen">
							<span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
						</a>
						<a data-toggle="tooltip" data-placement="top" title="Lock">
							<span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
						</a>
						<a data-toggle="tooltip" data-placement="top" title="Çıkış" asp-area"admin" asp-controller="Home" asp-action="Logout">
							<span class="glyphicon glyphicon-off" aria-hidden="true"></span>
						</a>
					</div>
					<!-- /menu footer buttons -->
				</div>
			</div>

			<!-- top navigation -->
			<div class="top_nav">
				<div class="nav_menu">
					<div class="nav toggle">
						<a id="menu_toggle"><i class="fa fa-bars"></i></a>
					</div>
					<nav class="nav navbar-nav">
						<ul class=" navbar-right">
							<li class="nav-item dropdown open" style="padding-left: 15px;">
								<a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
									<img src="/admin/images/img.jpg" alt="">@User.Claims.FirstOrDefault(x=>x.Type==ClaimTypes.Name).Value
								</a>
								<div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
									<a class="dropdown-item" href="javascript:;"> Profile</a>
									<a class="dropdown-item" href="javascript:;">
										<span class="badge bg-red pull-right">50%</span>
										<span>Settings</span>
									</a>
									<a class="dropdown-item" href="javascript:;">Help</a>
									<a asp-controller="Home" asp-action="Logout"><i class="fa fa-sign-out pull-right"></i>Çıkış</a>
								</div>
							</li>

							<li role="presentation" class="nav-item dropdown open">
								<a href="javascript:;" class="dropdown-toggle info-number" id="navbarDropdown1" data-toggle="dropdown" aria-expanded="false">
									<i class="fa fa-envelope-o"></i>
									<span class="badge bg-green">6</span>
								</a>
								<ul class="dropdown-menu list-unstyled msg_list" role="menu" aria-labelledby="navbarDropdown1">
									<li class="nav-item">
										<a class="dropdown-item">
											<span class="image"><img src="/admin/images/img.jpg" alt="Profile Image" /></span>
											<span>
												<span>John Smith</span>
												<span class="time">3 mins ago</span>
											</span>
											<span class="message">
												Film festivals used to be do-or-die moments for movie makers. They were where...
											</span>
										</a>
									</li>
									<li class="nav-item">
										<a class="dropdown-item">
											<span class="image"><img src="/admin/images/img.jpg" alt="Profile Image" /></span>
											<span>
												<span>John Smith</span>
												<span class="time">3 mins ago</span>
											</span>
											<span class="message">
												Film festivals used to be do-or-die moments for movie makers. They were where...
											</span>
										</a>
									</li>
									<li class="nav-item">
										<a class="dropdown-item">
											<span class="image"><img src="/admin/images/img.jpg" alt="Profile Image" /></span>
											<span>
												<span>John Smith</span>
												<span class="time">3 mins ago</span>
											</span>
											<span class="message">
												Film festivals used to be do-or-die moments for movie makers. They were where...
											</span>
										</a>
									</li>
									<li class="nav-item">
										<a class="dropdown-item">
											<span class="image"><img src="/admin/images/img.jpg" alt="Profile Image" /></span>
											<span>
												<span>John Smith</span>
												<span class="time">3 mins ago</span>
											</span>
											<span class="message">
												Film festivals used to be do-or-die moments for movie makers. They were where...
											</span>
										</a>
									</li>
									<li class="nav-item">
										<div class="text-center">
											<a class="dropdown-item">
												<strong>See All Alerts</strong>
												<i class="fa fa-angle-right"></i>
											</a>
										</div>
									</li>
								</ul>
							</li>
						</ul>
					</nav>
				</div>
			</div>
			<!-- /top navigation -->
			@RenderBody()

			<!-- footer content -->
			<footer>
				<div class="pull-right">
					Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
				</div>
				<div class="clearfix"></div>
			</footer>
			<!-- /footer content -->
		</div>
	</div>

	<!-- jQuery -->
	<script src="/admin/vendors/jquery/dist/jquery.min.js"></script>
	<!-- Bootstrap -->
	<script src="/admin/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<!-- FastClick -->
	<script src="/admin/vendors/fastclick/lib/fastclick.js"></script>
	<!-- NProgress -->
	<script src="/admin/vendors/nprogress/nprogress.js"></script>
	<!-- Chart.js -->
	<script src="/admin/vendors/Chart.js/dist/Chart.min.js"></script>
	<!-- gauge.js -->
	<script src="/admin/vendors/gauge.js/dist/gauge.min.js"></script>
	<!-- bootstrap-progressbar -->
	<script src="/admin/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
	<!-- iCheck -->
	<script src="/admin/vendors/iCheck/icheck.min.js"></script>
	<!-- Skycons -->
	<script src="/admin/vendors/skycons/skycons.js"></script>
	<!-- Flot -->
	<script src="/admin/vendors/Flot/jquery.flot.js"></script>
	<script src="/admin/vendors/Flot/jquery.flot.pie.js"></script>
	<script src="/admin/vendors/Flot/jquery.flot.time.js"></script>
	<script src="/admin/vendors/Flot/jquery.flot.stack.js"></script>
	<script src="/admin/vendors/Flot/jquery.flot.resize.js"></script>
	<!-- Flot plugins -->
	<script src="/admin/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
	<script src="/admin/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
	<script src="/admin/vendors/flot.curvedlines/curvedLines.js"></script>
	<!-- DateJS -->
	<script src="/admin/vendors/DateJS/build/date.js"></script>
	<!-- JQVMap -->
	<script src="/admin/vendors/jqvmap/dist/jquery.vmap.js"></script>
	<script src="/admin/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
	<script src="/admin/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
	<!-- bootstrap-daterangepicker -->
	<script src="/admin/vendors/moment/min/moment.min.js"></script>
	<script src="/admin/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
	<script src="/admin/vendors/jquery.validate.min.js"></script>
	<script src="/admin/vendors/jquery.validate.unobtrusive.js"></script>
	<!-- Custom Theme Scripts -->
	<script src="/admin/build/js/custom.min.js"></script>
	<script src="/ckeditor/ckeditor.js"></script>
	<script src="/admin/vendors/admin.js"></script>

</body>
</html>